from os import system
system("cls")
from turtle import pensize,color,bgcolor,shape,circle,fd,penup,pendown,sety,setx,done
pensize(1)
color("white")
bgcolor("black")
shape("turtle")
for x in range(2):
    circle(extent=90,radius=50)
    fd(180)
    circle(extent=90,radius=50)
    fd(350)
penup()
sety(100)
setx(-50)
pendown()
circle(radius=60)
setx(-300)
circle(radius=60)
penup()
sety(220)
pendown()
fd(260)
color("red")
done()