from os import system
system("cls")
name1=(input(">>"))
print(name1.replace(" ","💕")) if " " in name1 else print(f"hello ! {name1}")
number1=int(input("<<"))
print(f"Number School Parsa Naderi:{number1}") 
from turtle import color,pencolor,bgcolor,shape,shapesize,speed,circle,fd,lt,penup,pendown,setx,sety,done
color("cyan")
pencolor("cyan")
bgcolor("white")
shape("turtle")
shapesize(1)
for x in range(2):
    circle(extent=90,radius=50)
    fd(100)
    circle(extent=90,radius=40)
    fd(200)
penup()
setx(-20)
sety(10)
pendown()
circle(radius=30)
penup()
sety(70)
pendown()
lt(90)
fd(120)
for y in range(4):
    circle(extent=90,radius=0.25)
    fd(100)
for z in range(3):
    fd(100)
    lt(120)
done()